package com.ctfind.productioncontrol.auth.application

const val ORDER_MANAGER_ROLE_CODE = "ORDER_MANAGER"
const val WAREHOUSE_ROLE_CODE = "WAREHOUSE"
const val PRODUCTION_SUPERVISOR_ROLE_CODE = "PRODUCTION_SUPERVISOR"
const val PRODUCTION_EXECUTOR_ROLE_CODE = "PRODUCTION_EXECUTOR"

val SUPPORTED_ROLE_CODES: Set<String> = setOf(
	"ADMIN",
	ORDER_MANAGER_ROLE_CODE,
	WAREHOUSE_ROLE_CODE,
	PRODUCTION_SUPERVISOR_ROLE_CODE,
	PRODUCTION_EXECUTOR_ROLE_CODE,
)
