spring.application.name=ctfind-production-control-contlin

ctfind.auth.superadmin.login=${APP_SUPERADMIN_LOGIN:}
ctfind.auth.superadmin.display-name=${APP_SUPERADMIN_DISPLAY_NAME:}
ctfind.auth.superadmin.password=${APP_SUPERADMIN_PASSWORD:}
