spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/ctfind_contlin}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:ctfind}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:ctfind}

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false

spring.flyway.enabled=true

management.endpoints.web.exposure.include=health
management.endpoint.health.show-details=never
