/**
 * Codegen TypeScript-интерфейсов из DocType JSON-файлов custom-app'а.
 * Запуск: pnpm gen:types
 *
 * Источник: ../ctfind_production_control/production_control/doctype/<dt>/<dt>.json
 * Цель:     src/api/types/frappe.generated.ts
 */
import { existsSync, mkdirSync, readdirSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

const __dirname = dirname(fileURLToPath(import.meta.url))
const DOCTYPE_ROOT = resolve(
  __dirname,
  '../../ctfind_production_control/production_control/doctype',
)
const OUT_FILE = resolve(__dirname, '../src/api/types/frappe.generated.ts')

interface DocTypeField {
  fieldname: string
  fieldtype: string
  label?: string
  options?: string
  reqd?: 0 | 1
  read_only?: 0 | 1
}

interface DocTypeJSON {
  doctype: 'DocType'
  name?: string
  istable?: 0 | 1
  autoname?: string
  fields: DocTypeField[]
}

interface ParsedDoctype {
  rawName: string
  pyClassName: string
  isChildTable: boolean
  fields: DocTypeField[]
}

const TS_TYPE_BY_FIELDTYPE: Record<string, string> = {
  'Data': 'string',
  'Small Text': 'string',
  'Long Text': 'string',
  'Text': 'string',
  'Text Editor': 'string',
  'Code': 'string',
  'Markdown': 'string',
  'HTML': 'string',
  'HTMLEditor': 'string',
  'Link': 'string',
  'Dynamic Link': 'string',
  'Password': 'string',
  'ReadOnly': 'string',
  'Date': 'string',
  'Datetime': 'string',
  'Time': 'string',
  'Int': 'number',
  'Float': 'number',
  'Currency': 'number',
  'Percent': 'number',
  'Check': '0 | 1',
  'Attach': 'string',
  'Attach Image': 'string',
  'Color': 'string',
  'Phone': 'string',
  'Email': 'string',
  'URL': 'string',
  'Signature': 'string',
  'Duration': 'string',
  'JSON': 'string',
  'Geolocation': 'string',
  'Rating': 'number',
  'Barcode': 'string',
}

const SECTION_FIELDTYPES = new Set([
  'Section Break',
  'Column Break',
  'Tab Break',
  'Heading',
  'Fold',
])

function pascalCase(name: string): string {
  return name
    .replace(/[^\w ]/g, '')
    .split(/[\s_]+/)
    .map(w => w.charAt(0).toUpperCase() + w.slice(1).toLowerCase())
    .join('')
}

function fieldTypeToTs(field: DocTypeField, childTableLookup: Map<string, string>): string {
  if (field.fieldtype === 'Select' && field.options) {
    const options = field.options
      .split('\n')
      .map(o => o.trim())
      .filter(Boolean)
    if (options.length === 0)
      return 'string'
    return options.map(o => JSON.stringify(o)).join(' | ')
  }
  if (field.fieldtype === 'Table' || field.fieldtype === 'Table MultiSelect') {
    const child = field.options ? childTableLookup.get(field.options) : null
    return child ? `${child}[]` : 'unknown[]'
  }
  return TS_TYPE_BY_FIELDTYPE[field.fieldtype] ?? 'string'
}

function isFieldOptional(field: DocTypeField): boolean {
  if (field.reqd === 1)
    return false
  return true
}

function loadDoctypes(): ParsedDoctype[] {
  if (!existsSync(DOCTYPE_ROOT)) {
    throw new Error(`DocType root not found: ${DOCTYPE_ROOT}`)
  }
  const dirs = readdirSync(DOCTYPE_ROOT, { withFileTypes: true })
    .filter(d => d.isDirectory() && !d.name.startsWith('_'))
    .map(d => d.name)

  const parsed: ParsedDoctype[] = []
  for (const dirName of dirs) {
    const jsonPath = resolve(DOCTYPE_ROOT, dirName, `${dirName}.json`)
    if (!existsSync(jsonPath))
      continue
    const raw = JSON.parse(readFileSync(jsonPath, 'utf-8')) as DocTypeJSON
    if (raw.doctype !== 'DocType')
      continue
    const rawName = raw.name ?? dirName
    parsed.push({
      rawName,
      pyClassName: pascalCase(rawName),
      isChildTable: raw.istable === 1,
      fields: (raw.fields ?? []).filter(f => !SECTION_FIELDTYPES.has(f.fieldtype)),
    })
  }
  return parsed
}

function emit(doctypes: ParsedDoctype[]): string {
  const childTableLookup = new Map<string, string>()
  for (const dt of doctypes) {
    if (dt.isChildTable) {
      childTableLookup.set(dt.rawName, dt.pyClassName)
    }
  }

  const lines: string[] = []
  lines.push('/* eslint-disable */')
  lines.push('/**')
  lines.push(' * AUTO-GENERATED by scripts/gen-types.ts.')
  lines.push(' * НЕ РЕДАКТИРОВАТЬ ВРУЧНУЮ. Регенерация: pnpm gen:types.')
  lines.push(' * Источник: production_control/doctype/<dt>/<dt>.json')
  lines.push(' */')
  lines.push('')
  lines.push('export interface FrappeBaseDoc {')
  lines.push('  name: string')
  lines.push('  owner: string')
  lines.push('  creation: string')
  lines.push('  modified: string')
  lines.push('  modified_by: string')
  lines.push('  docstatus: 0 | 1 | 2')
  lines.push('  idx?: number')
  lines.push('  parent?: string')
  lines.push('  parenttype?: string')
  lines.push('  parentfield?: string')
  lines.push('}')
  lines.push('')

  for (const dt of doctypes) {
    lines.push(`/** DocType: ${dt.rawName}${dt.isChildTable ? ' (child table)' : ''} */`)
    lines.push(`export interface ${dt.pyClassName} extends FrappeBaseDoc {`)
    for (const f of dt.fields) {
      const tsType = fieldTypeToTs(f, childTableLookup)
      const opt = isFieldOptional(f) ? '?' : ''
      const comment = f.label ? ` // ${f.label}` : ''
      lines.push(`  ${f.fieldname}${opt}: ${tsType}${comment}`)
    }
    lines.push('}')
    lines.push('')
  }

  lines.push('/** Frappe core: Version */')
  lines.push('export interface FrappeVersion {')
  lines.push('  name: string')
  lines.push('  ref_doctype: string')
  lines.push('  docname: string')
  lines.push('  data: string')
  lines.push('  owner: string')
  lines.push('  creation: string')
  lines.push('}')
  lines.push('')

  return lines.join('\n')
}

function main(): void {
  const doctypes = loadDoctypes()
  if (doctypes.length === 0) {
    console.error('No DocTypes found at', DOCTYPE_ROOT)
    process.exit(1)
  }
  const output = emit(doctypes)
  mkdirSync(dirname(OUT_FILE), { recursive: true })
  writeFileSync(OUT_FILE, output, 'utf-8')
  console.log(`✓ Generated ${doctypes.length} DocType interface(s) → ${OUT_FILE}`)
}

main()
