/* eslint-disable */
/**
 * AUTO-GENERATED by scripts/gen-types.ts.
 * НЕ РЕДАКТИРОВАТЬ ВРУЧНУЮ. Регенерация: pnpm gen:types.
 * Источник: production_control/doctype/<dt>/<dt>.json
 */

export interface BaseDoc {
  name: string
  owner: string
  creation: string
  modified: string
  modified_by: string
  docstatus: 0 | 1 | 2
  idx?: number
  parent?: string
  parenttype?: string
  parentfield?: string
}

/** DocType: Access Audit Event */
export interface AccessAuditEvent extends BaseDoc {
  event_type: "login-success" | "login-failed" | "user-created" | "user-disabled" | "roles-changed" | "access-ended" // Event Type
  event_at: string // Event At
  source_surface?: "login-form" | "user-admin" | "role-admin" | "session-management" // Source Surface
  event_summary: string // Event Summary
  actor_user?: string // Actor User
  target_user?: string // Target User
  target_staff_member?: string // Target Staff Member
}

/** DocType: Customer */
export interface Customer extends BaseDoc {
  customer_name: string // Наименование клиента
  status: "active" | "inactive" // Статус
  contact_person?: string // Контактное лицо
  phone?: string // Телефон
  email?: string // Email
}

/** DocType: Customer Order */
export interface CustomerOrder extends BaseDoc {
  customer: string // Клиент
  delivery_date: string // Срок исполнения
  status: "новый" | "в работе" | "готов" | "отгружен" // Статус
  items: CustomerOrderItem[] // Позиции
  notes?: string // Комментарий к заказу
  created_by_staff?: string // Создатель (сотрудник)
  amended_from?: string // Amended From
}

/** DocType: Customer Order Item (child table) */
export interface CustomerOrderItem extends BaseDoc {
  item_name: string // Наименование
  quantity: number // Количество
  uom: string // Ед. измерения
}

/** DocType: Customer Order Status Change */
export interface CustomerOrderStatusChange extends BaseDoc {
  order: string // Заказ
  from_status?: string // Из статуса
  to_status: string // В статус
  actor_user: string // Актёр
  event_at: string // Момент перехода
  via_admin_correction?: 0 | 1 // Админ-коррекция
  note?: string // Комментарий
}

/** DocType: Staff Member */
export interface StaffMember extends BaseDoc {
  staff_code: string // Staff Code
  full_name: string // Full Name
  business_role_label?: string // Business Role Label
  department_or_zone?: string // Department Or Zone
  phone?: string // Phone
  email?: string // Email
  directory_status: "active" | "inactive" | "archived" // Directory Status
  access_status: "not-issued" | "active" | "suspended" | "revoked" // Access Status
  linked_user?: string // Linked User
}

/** Core audit/version row */
export interface VersionRow {
  name: string
  ref_doctype: string
  docname: string
  data: string
  owner: string
  creation: string
}
